### ISSUE TITLE
When trying to run the xr flags, the app panics.

### ISSUE THREAD

**Issue by 2-3-5-41** [philpax/wgpu-openxr-example#11]
# Error logs

```
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : ApiLayerInterface::LoadApiLayers - failed to find layer XR_APILAYER_LUNARG_core_validation
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : Failed loading layer information
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : xrCreateInstance failed
Error: a requested API layer is not present or could not be loaded
error: process didn't exit successfully: `target\debug\wgpu-openxr-example.exe desktop-with-xr-resolution` (exit code: 1)
```

# Hardware and software

- Valve index
- SteamVR (stable and beta versions tested)
- Windows 11
- Radeon RX 6800 XT
- Driver version 22.5.1

**Comment by hrolfurgylfa** [comment]
I'm also getting the same error when I run either desktop-with-xr-resolution or xr.

When I run desktop it doesn't crash but I'm getting a lot of errors from Vulcan:

```
2022-11-21T00:56:35.732349Z ERROR wgpu_hal::vulkan::instance: VALIDATION [VUID-VkSubpassDescription2-multiview-06558 (0x449380de)]
        Validation Error: [ VUID-VkSubpassDescription2-multiview-06558 ] Object 0: handle = 0x17047bf2030, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x449380de | vkCreateRenderPass(): pCreateInfo->pSubpasses[0].viewMask is 3, but multiview feature is not enabled. The Vulkan spec states: If the multiview feature is not enabled, viewMask must be 0 (https://vulkan.lunarg.com/doc/view/1.3.211.0/windows/1.3-extensions/vkspec.html#VUID-VkSubpassDescription2-multiview-06558)
2022-11-21T00:56:35.732550Z ERROR wgpu_hal::vulkan::instance:   objects: (type: DEVICE, hndl: 0x17047bf2030, name: ?)

2022-11-21T00:56:35.732894Z ERROR wgpu_hal::vulkan::instance: VALIDATION [VUID-VkShaderModuleCreateInfo-pCode-01091 (0xa7bb8db6)]
        Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01091 ] Object 0: handle = 0x17047bf2030, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa7bb8db6 | vkCreateShaderModule(): The SPIR-V Capability (MultiView) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.3.211.0/windows/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01091)
2022-11-21T00:56:35.733019Z ERROR wgpu_hal::vulkan::instance:   objects: (type: DEVICE, hndl: 0x17047bf2030, name: ?)

2022-11-21T00:56:35.756628Z ERROR wgpu_hal::vulkan::instance: VALIDATION [VUID-VkSubpassDescription2-multiview-06558 (0x449380de)]
        Validation Error: [ VUID-VkSubpassDescription2-multiview-06558 ] Object 0: handle = 0x17047bf2030, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x449380de | vkCreateRenderPass(): pCreateInfo->pSubpasses[0].viewMask is 3, but multiview feature is not enabled. The Vulkan spec states: If the multiview feature is not enabled, viewMask must be 0 (https://vulkan.lunarg.com/doc/view/1.3.211.0/windows/1.3-extensions/vkspec.html#VUID-VkSubpassDescription2-multiview-06558)
2022-11-21T00:56:35.756804Z ERROR wgpu_hal::vulkan::instance:   objects: (type: DEVICE, hndl: 0x17047bf2030, name: ?)

2022-11-21T00:56:35.756995Z ERROR wgpu_hal::vulkan::instance: VALIDATION [VUID-VkShaderModuleCreateInfo-pCode-01091 (0xa7bb8db6)]
        Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01091 ] Object 0: handle = 0x17047bf2030, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa7bb8db6 | vkCreateShaderModule(): The SPIR-V Capability (MultiView) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.3.211.0/windows/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01091)
2022-11-21T00:56:35.757141Z ERROR wgpu_hal::vulkan::instance:   objects: (type: DEVICE, hndl: 0x17047bf2030, name: ?)

2022-11-21T00:56:35.759794Z ERROR wgpu_hal::vulkan::instance: VALIDATION [VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 (0x7cd0911d)]
        Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x17047bf2030, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (1424,714), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (800,600), minImageExtent = (800,600), maxImageExtent = (800,600). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://vulkan.lunarg.com/doc/view/1.3.211.0/windows/1.3-extensions/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
2022-11-21T00:56:35.759940Z ERROR wgpu_hal::vulkan::instance:   objects: (type: DEVICE, hndl: 0x17047bf2030, name: ?)

2022-11-21T00:56:35.771772Z ERROR wgpu_hal::vulkan::instance: VALIDATION [VUID-VkSubpassDescription2-multiview-06558 (0x449380de)]
        Validation Error: [ VUID-VkSubpassDescription2-multiview-06558 ] Object 0: handle = 0x17047bf2030, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x449380de | vkCreateRenderPass(): pCreateInfo->pSubpasses[0].viewMask is 3, but multiview feature is not enabled. The Vulkan spec states: If the multiview feature is not enabled, viewMask must be 0 (https://vulkan.lunarg.com/doc/view/1.3.211.0/windows/1.3-extensions/vkspec.html#VUID-VkSubpassDescription2-multiview-06558)
2022-11-21T00:56:35.771958Z ERROR wgpu_hal::vulkan::instance:   objects: (type: DEVICE, hndl: 0x17047bf2030, name: ?)

2022-11-21T00:56:35.772169Z ERROR wgpu_hal::vulkan::instance: VALIDATION [VUID-VkFramebufferCreateInfo-renderPass-02531 (0xae537265)]
        Validation Error: [ VUID-VkFramebufferCreateInfo-renderPass-02531 ] Object 0: handle = 0x1d4e2e0000000062, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0xae537265 | vkCreateFramebuffer(): VkFramebufferCreateInfo has #2 layers but renderPass (VkRenderPass 0x1d4e2e0000000062[]) was specified with non-zero view masks
 The Vulkan spec states: If renderPass was specified with non-zero view masks, layers must be 1 (https://vulkan.lunarg.com/doc/view/1.3.211.0/windows/1.3-extensions/vkspec.html#VUID-VkFramebufferCreateInfo-renderPass-02531)
2022-11-21T00:56:35.772304Z ERROR wgpu_hal::vulkan::instance:   objects: (type: RENDER_PASS, hndl: 0x1d4e2e0000000062, name: ?)
```

I also tried removing "XR_APILAYER_LUNARG_core_validation" from the list in xr.rs line 80 but that resulted in failure to create the Vulcan instance without much more information on why:

```
...
2022-11-21T01:11:18.752711Z  INFO wgpu_openxr_example::xr: available xr layers: []
2022-11-21T01:11:19.382256Z  INFO wgpu_openxr_example::xr: loaded OpenXR runtime: SteamVR/OpenXR 0.1.0 SteamVR/OpenXR : oculus
2022-11-21T01:11:19.410621Z  INFO wgpu_openxr_example::xr: creating vulkan instance with these extensions: [
    "VK_KHR_surface",
    "VK_KHR_win32_surface",
    "VK_KHR_get_physical_device_properties2",
    "VK_EXT_swapchain_colorspace",
    "VK_KHR_swapchain",
]
Error: XR error creating Vulkan instance

Caused by:
    the runtime failed to handle the function in an unexpected way that is not covered by another error result
error: process didn't exit successfully: `target\debug\wgpu-openxr-example.exe xr` (exit code: 1)
```

### System:
* Quest 2
* SteamVR (through ALVR)
* Windows 11
* NVidea RTX 3060

**Comment by PZerua** [comment]
Hi! I'm facing the same issue, did you manage to workaround/fix this?

I'm using a Quest2 and executing the application through Oculus Link.

**Comment by niconulla** [comment]
I think I have a similar problem, on Manjaro linux with an HTC Vive.

<details><summary>Compiling produces this error message</summary>
<blockquote>error: failed to run custom build command for `openxr-sys v0.9.2`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/user/github/wgpu-openxr-example.bak/target/release/build/openxr-sys-e42805b7d55f099e/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/home/user/github/wgpu-openxr-example.bak/target/release/build/openxr-sys-7564ce4912ce6043/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openxr-sys-0.9.2/OpenXR-SDK" "-DBUILD_API_LAYERS=OFF" "-DBUILD_TESTS=OFF" "-DOpenGL_GL_PREFERENCE=GLVND" "-DDYNAMIC_LOADER=OFF" "-DCMAKE_INSTALL_LIBDIR=lib" "-DCMAKE_INSTALL_PREFIX=/home/user/github/wgpu-openxr-example.bak/target/release/build/openxr-sys-7564ce4912ce6043/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"
  -- The C compiler identification is GNU 13.1.1
  -- The CXX compiler identification is GNU 13.1.1
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.11.3", minimum required is "3") 
  -- Performing Test HAVE_FILESYSTEM_WITHOUT_LIB
  -- Performing Test HAVE_FILESYSTEM_WITHOUT_LIB - Success
  -- Performing Test HAVE_FILESYSTEM_NEEDING_LIBSTDCXXFS
  -- Performing Test HAVE_FILESYSTEM_NEEDING_LIBSTDCXXFS - Success
  -- Performing Test HAVE_FILESYSTEM_NEEDING_LIBCXXFS
  -- Performing Test HAVE_FILESYSTEM_NEEDING_LIBCXXFS - Failed
  -- Found OpenGL: /usr/lib/libOpenGL.so   
  -- Enabling OpenGL support
  -- Found Vulkan: /lib/libvulkan.so (found version "1.3.256") found components: glslc glslangValidator 
  -- Enabling Vulkan support
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
  -- Found Threads: TRUE  
  -- Found JsonCpp: /usr/include  
  -- Presentation backend selected for hello_xr, loader_test, conformance: xlib
  -- Found X11: /usr/include   
  -- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
  -- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
  -- Looking for gethostbyname
  -- Looking for gethostbyname - found
  -- Looking for connect
  -- Looking for connect - found
  -- Looking for remove
  -- Looking for remove - found
  -- Looking for shmat
  -- Looking for shmat - found
  -- Looking for IceConnectionNumber in ICE
  -- Looking for IceConnectionNumber in ICE - found
  -- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
  -- Checking for one of the modules 'xcb;xcb-glx'
  -- Checking for one of the modules 'wayland-client'
  -- BUILD_WITH_XLIB_HEADERS: ON
  -- BUILD_WITH_XCB_HEADERS: ON
  -- BUILD_WITH_WAYLAND_HEADERS: ON
  -- Found glslc: /usr/bin/glslc
  -- Looking for secure_getenv
  -- Looking for secure_getenv - found
  -- Looking for __secure_getenv
  -- Looking for __secure_getenv - not found
  -- Looking for timespec_get
  -- Looking for timespec_get - found
  -- Found and will use pre-generated xr_generated_dispatch_table.h in source tree
  -- Found and will use pre-generated xr_generated_dispatch_table.c in source tree
  -- Performing Test SUPPORTS_Wall
  -- Performing Test SUPPORTS_Wall - Success
  -- Performing Test SUPPORTS_C_Wall
  -- Performing Test SUPPORTS_C_Wall - Success
  -- Performing Test SUPPORTS_Werrorunusedparameter
  -- Performing Test SUPPORTS_Werrorunusedparameter - Success
  -- Performing Test SUPPORTS_C_Werrorunusedparameter
  -- Performing Test SUPPORTS_C_Werrorunusedparameter - Success
  -- Performing Test SUPPORTS_Werrorunusedargument
  -- Performing Test SUPPORTS_Werrorunusedargument - Failed
  -- Performing Test SUPPORTS_C_Werrorunusedargument
  -- Performing Test SUPPORTS_C_Werrorunusedargument - Failed
  -- Performing Test SUPPORTS_Wpointerarith
  -- Performing Test SUPPORTS_Wpointerarith - Success
  -- Performing Test SUPPORTS_C_Wpointerarith
  -- Performing Test SUPPORTS_C_Wpointerarith - Success
  -- Found and will use pre-generated xr_generated_loader.hpp in source tree
  -- Found and will use pre-generated xr_generated_loader.cpp in source tree
  -- Configuring done (4.6s)
  -- Generating done (0.0s)

  --- stderr
  CMake Warning (dev) at src/loader/CMakeLists.txt:48 (add_library):
    Policy CMP0063 is not set: Honor visibility properties for all target
    types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
    cmake_policy command to set the policy and suppress this warning.

    Target "openxr_loader" of type "STATIC_LIBRARY" has the following
    visibility properties set for C:

      C_VISIBILITY_PRESET

    For compatibility CMake is not honoring them for this target.
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Error: install(EXPORT "openxr_loader_export" ...) includes target "openxr_loader" which requires target "jsoncpp_interface" that is not in any export set.
  CMake Error in src/loader/CMakeLists.txt:
    export called with target "openxr_loader" which requires target
    "jsoncpp_interface" that is not in any export set.


  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_COMPILER
      CMAKE_ASM_FLAGS


  CMake Generate step failed.  Build files cannot be regenerated correctly.
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1

  build script failed, must exit now', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.48/src/lib.rs:975:5
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
     1: core::panicking::panic_fmt
               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
     2: cmake::fail
     3: cmake::run
     4: cmake::Config::build
     5: build_script_build::main
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</blockquote></details>

..and removing the "static" feature from the openxr crate lets it build, but gives this error on running "xr" (the "desktop" version runs correctly):

<blockquote>Core Validation output type: text, first time = true
Error: XR error creating Vulkan instance

Caused by:
    the runtime failed to handle the function in an unexpected way that is not covered by another error result
</blockquote>

**Comment by BleyChimera** [comment]
I am also getting the exact same errors as the ones in the opening issue.
SteamVR doesn't startup and it doesn't seem to interact with the program even if started up.

I think we simply don't have some dll needed to use this version of OpenXR?
Or maybe is some path somewhere that is broken?
